### ISSUE TITLE
Configuration language examples

### ISSUE THREAD

**Issue by knoepfel** [HEPCloud/decisionengine#102]
A recommendation will be made to the HEPCloud developers on June 4, 2020 regarding the configuration language.  Please [download the tarball](https://github.com/HEPCloud/decisionengine/files/4725297/configuration-examples.tar.gz) here to compare current configurations with those represented in the new language.

**Comment by StevenCTimm** [comment]
Have reviewed the configuration changes as made by the configuration developers.  They all work.
