### ISSUE TITLE
log_level issues in new decisionengine 1.2.0-1

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#109]
I am trying to test the new functionality which was implemented for issue !84.  

The logger section of the /etc/decisionengine/decision_engine.conf  is below

 'logger' : {'log_file': '/var/log/decisionengine/decision_engine_log',
                'max_file_size': 200*1000000,
                'max_backup_count': 6,
                'log_level': "DEBUG",
     },

But although I am running seven channels I do not see any DEBUG entries in any of the logs.

Is any further configuration necessary?

Also what is the syntax to set the log level on a channel by channel basis.

This is set up on fermicloud117.fnal.gov right now, I can give root login if needed.

Steve Timm

**Comment by DmitryLitvintsev** [comment]
The config specified log level is "global" setting for all channels. 
Individual channels should be able to have their logo level changed at runtime using de-client command 

( do de-client --help) 

Can you verify that you can manipulate long level using de-client command?

The log level changed using de-client is not persistent. Nor there is currently provision in config 
to have different log levels per channel at startup. I considered that to be extraneous,. But it is up to discussion of course.

**Comment by StevenCTimm** [comment]
[root@fermicloud117 decisionengine]# de-client --print-engine-loglevel
DEBUG
[root@fermicloud117 decisionengine]# de-client --status | grep state
channel: Nersc                              , id = 218B5545-31FC-4F20-91EA-90439B75937D, state = STEADY     
channel: AWS_Calculations_with_source_proxy , id = 357C9220-7B62-4E50-A7CC-62F8095A351D, state = STEADY     
channel: sample_gcebilling                  , id = 34BA8394-0631-4DC0-84F5-BD0EF21648BD, state = STEADY     
channel: Gce                                , id = C0887C4D-ABA9-4BBD-9780-2162649E448F, state = STEADY     
channel: channel_aws_config_data            , id = 68F163F5-BBE8-48BC-9B61-57EEC5E5D90C, state = STEADY     
channel: AWSbilling                         , id = ED98E162-3FFA-445E-AD1A-29453EAE999C, state = STEADY     
channel: job_classification                 , id = C8A08F40-2113-41FC-9ED3-7C8B2A4A2C6D, state = STEADY     
	state: State.SLEEPING
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel Nersc
INFO
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel AWS_Calculations_with_source_proxy
INFO
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel sample_gcebilling
INFO
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel Gce
INFO
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel channel_aws_config_data
INFO
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel AWSbilling
INFO
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel job_classification
INFO
[root@fermicloud117 decisionengine]# de-client --set-channel-loglevel AWSbilling DEBUG
Log level changed to : DEBUG
[root@fermicloud117 decisionengine]# de-client --get-channel-loglevel AWSbilling
DEBUG

OK so I have set 2 channels to DEBUG, AWSbilling and job_classification.. we will see if I actually get any DEBUG entries now in the channel logs

So are you saying that the log_level in the decision_engine.conf only controls the 
decision_engine_log and decision_engine_log_debug themselves?  because there are no DEBUG statements in those log files either.

**Comment by DmitryLitvintsev** [comment]
There is misunderstanding. I asked Lisa to implement setting log levels from config file. But I did not explain that this setting need to apply to all channels. 

So now it sets level for decision_engine_log and log level for channels remains hardcoded to INFO. Lisa will fix it.

**Comment by StevenCTimm** [comment]
I have now set all 7 channels to DEBUG via the command line.  on four of them I have observed DEBUG output so far.. on three others I have not.. the puzzling one is job_classification.log which runs every minute.  The other two haven't run again yet since I changed the options.

**Comment by DmitryLitvintsev** [comment]
here are all the modules that print something at debug:

```
AWS/sources/AWSOccupancy.py
AWS/sources/AWSOccupancyWithSourceProxy.py
AWS/sources/BillingInfo.py
GCE/sources/GCEBillingInfo.py
glideinwms/glide_frontend_element.py
glideinwms/security.py
glideinwms/transforms/glidein_requests.py
glideinwms/transforms/job_clustering.py

framework/modules/SourceProxy.py
framework/modules/de_logger.py
framework/taskmanager/TaskManager.py

mac-131313:decisionengine dmitrylitvintsev$ grep '\.debug' framework/taskmanager/TaskManager.py
        logging.getLogger().debug('data_block_put %s', data)
            logging.getLogger().debug('Duplicated block {}'.format(data_block))
        logging.getLogger().debug('run_transforms: data block %s', data_block)
                    logging.getLogger().debug('transform returned %s', data)
            logging.getLogger().debug('run logic engine %s %s',
                logging.getLogger().debug('run publisher %s %s',

```

Nothing of this kind?

**Comment by StevenCTimm** [comment]
I see run logic engine, run publisher, in the 4 channels I mentioned above but not in the other 3

**Comment by StevenCTimm** [comment]
Dmitry made the comment in slack

There is evidence that none of the log statemements made in the modules themselves get printed in the log file . I only mesages made in TaskManager.py  but not in the modules. There mat be some fundamental flaw here which needs to be understood

I agree on this.. in the BillingInfo.py on fermicloud117 I have activated all of the debug verbose flags and nothing is printing out, neither to the AWSbilling.log or to the startup.log.
Further I have added print statements and those are not coming through either.
It will be difficult to solve decisionengine_modules #240 without getting this logging issue fixed first.

In the python 2.7 branch (at least for some sources) this is not the case, we do see output from the modules themselves in the log file, at least from glideinwms/glide_frontend_element.py

**Comment by StevenCTimm** [comment]
I have successfully gotten at least one self.logger.debug message from inside a channel into a log file.  That doesn't explain everything though.

**Comment by DmitryLitvintsev** [comment]
Here is the culprit:

python2 :

```
[root@fermicloud117 ~]# python DEAccountContants.py
('accountName', 'CMS', <type 'str'>)
('accountNumber', 486926498429, <type 'int'>)
('credentialsProfileName', 'BillingCMS', <type 'str'>)
('lastKnownBillDate', '01/01/20 00:00', <type 'str'>)
('balanceAtDate', 221753.42, <type 'float'>)
('costRatePerHourInLastSixHoursAlarmThreshold', 2, <type 'int'>)
('costRatePerHourInLastDayAlarmThreshold', 2, <type 'int'>)
('applyDiscount', True, <type 'bool'>)
('emailReceipientForAlarms', 'fermilab-cloud-facility-cms@fnal.gov', <type 'str'>)
...
```

vs python3:

```
[root@fermicloud117 ~]# python3 DEAccountContants.py
[root@fermicloud117 ~]# echo $?
0
```

That class does not load `/etc/decisionengine/modules.conf/AccountConstants_my.py` properly

**Comment by StevenCTimm** [comment]
that is true because the blank accounts hash shows that it already failed.
but how does it know where to get the configuration files--the variable should be passed from the config.

According to the code if you just call main it will load from AccountConstants_Sample.py 
but in the acquire method it should be using the config file variables

{ "sources"  : {
    "BillingInfo" : {
        "module" :  "decisionengine_modules.AWS.sources.BillingInfo",
        "name"   :  "BillingInfo",
                    "parameters": {
                        "billing_configuration": "/etc/decisionengine/modules.conf/AccountConstants_my.py",
			"dst_dir_for_s3_files":"/var/lib/decisionengine/awsfiles",
                    },
                    "schedule": 360,
    },


How do we call that from the CLI

?

**Comment by StevenCTimm** [comment]
and also are we ever going to spell-check this miserable routine?

**Comment by StevenCTimm** [comment]
I think we are going to hit that there's one malformed entry in the dict and that is what is making python3 silently burp.. next step is to cut back to one entry in the dict and see if the problem still persists.

**Comment by StevenCTimm** [comment]
ok--it actually matters what directory you are in when you execute.. that is even weirder
[root@fermicloud117 ~]# python3
Python 3.6.8 (default, Apr  1 2020, 10:29:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import DEAccountContants
>>> DEAccountContants.load_constants('/etc/decisionengine/modules.conf/AccountConstants_my.py')
config_dict={'AWSNOvAAccountConstants': 
        {
        'lastKnownBillDate': '01/01/20 00:00', # '%m/%d/%y %H:%M'
        'balanceAtDate': 4197.95,  # $
        'accountName': 'NOvA',
        'accountNumber': 950490332792,
        'credentialsProfileName': 'BillingNOvA',
        'applyDiscount': False, # DLT discount does not apply to credits
        'costRatePerHourInLastSixHoursAlarmThreshold': 2, # $ / h # up to $180/h
        'costRatePerHourInLastDayAlarmThreshold': 2, # $ / h # up to $180/h
        'emailReceipientForAlarms': 'fermilab-cloud-facility-nova@fnal.gov',
        },
 'AWSRnDAccountConstants': 
        {
        'lastKnownBillDate': '01/01/20 00:00', # '%m/%d/%y %H:%M'
        'balanceAtDate': 5000.00,    # $ 
        'accountName': 'RnD',
        'accountNumber': 159067897602,
        'credentialsProfileName':'BillingRnD',
        'applyDiscount': True, # DLT discount does not apply to credits
        'costRatePerHourInLastSixHoursAlarmThreshold': 10, # $ / h # $10/h
        'costRatePerHourInLastDayAlarmThreshold': 10, # $ / h # $10/h
        'emailReceipientForAlarms': 'fermilab-cloud-facility-rnd@fnal.gov'
        },
 'AWSCMSAccountConstants':
        {
        'lastKnownBillDate': '01/01/20 00:00', # '%m/%d/%y %H:%M'
        'balanceAtDate': 221753.42,     # $ 
        'accountName': 'CMS',
        'accountNumber': 486926498429,
        'credentialsProfileName': 'BillingCMS',
        'applyDiscount': True, # DLT discount does not apply to credits
        'costRatePerHourInLastSixHoursAlarmThreshold': 2, # $ / h # up to $1000/h
        'costRatePerHourInLastDayAlarmThreshold': 2, # $ / h # up to $1000/h
        'emailReceipientForAlarms': 'fermilab-cloud-facility-cms@fnal.gov'
        },
 'AWSFermilabAccountConstants':
        {
        'lastKnownBillDate': '01/01/20 00:00', # '%m/%d/%y %H:%M'
        'balanceAtDate': 95297.54,       # $ 
        'accountName': 'Fermilab',
        'accountNumber': 229161804233,
        'credentialsProfileName': 'BillingFermilab',
        'applyDiscount': True, # DLT discount does not apply to credits
        'costRatePerHourInLastSixHoursAlarmThreshold': 100, # $ / h # $1/h
        'costRatePerHourInLastDayAlarmThreshold': 100, # $ / h # $1/h
        'emailReceipientForAlarms': 'fermilab-cloud-facility-fermilab@fnal.gov'
        },
 }

CONFIG DICT {}
{}
>>> 
[root@fermicloud117 ~]# cd /usr/lib/python3.6/site-packages/decisionengine_modules/AWS/sources/
[root@fermicloud117 sources]# python3
Python 3.6.8 (default, Apr  1 2020, 10:29:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import DEAccountContants.py 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'DEAccountContants.py'; 'DEAccountContants' is not a package
>>> import DEAccountContants
>>> DEAccountContants.load_constants('/etc/decisionengine/modules.conf/AccountConstants_my.py')
{}

**Comment by DmitryLitvintsev** [comment]
I have fixed it on fermicloud117. The difference in `exec` call between python2 and python3

you can restart channel and see of you get downloaded files.

**Comment by StevenCTimm** [comment]
It got a bit farther--it downloaded one of the four sets of files

**Comment by DmitryLitvintsev** [comment]
yes, then there will be more exceptions . Crap.

**Comment by DmitryLitvintsev** [comment]
I will fix it eventually

**Comment by StevenCTimm** [comment]
About half of the above comments in this issue are actually part of the closed issue #240, Dmitry and I were working 2 separate issues and we got confused.

**Comment by StevenCTimm** [comment]
I am now testing a CI rpm from master as compiled July 2.
I used de-client --set-channel-loglevel to set the log level of the 5 currently running channels to DEBUG.
Thus far I have seen proper DEBUG messages from the Gce and Nersc channels.

Two others (sample_gcebilling and AWSbilling) have put out no log messages whatsoever but this may be expected because they run on a very long schedule.


I have opened a new issue because now it seems there is a problem with the DEBUG setting of the main framework--namely that you can set it but it has no effect.

I need clarification on one other thing--for individual channels how are we supposed to set the DEBUG by config file.

**Comment by DmitryLitvintsev** [comment]
No setting per channel is foreseen. config provides master debug level for all channels. You cab set individual channels to 
DEBUG using  

```
de-client --set-channel-loglevel 
```
Why is this? I think setting by channel would make config rather messy with little benefit. Need to debug channel - set it run time from command line else set master log level to DEBUG in config.

**Comment by StevenCTimm** [comment]
The reason I asked about an initial setting of DEBUG for a channel is because oftentimes a channel can start and crash before you can type de-client --set-channel-loglevel
And if I understand it, the --set-channel-loglevel is not sticky, you have to do it every time you restart the channel.

As far as the main debug level in /etc/decisionengine/decision_engine.conf, that does not affect the channel.
I have that set, but the individual channels still defaulted to WARN and individual channels only contained WARN or higher until I did the --set-channel-loglevel.

**Comment by goodenou** [comment]
I will look into this issue of the channel settings defaulting to WARN.

**Comment by DmitryLitvintsev** [comment]
> The reason I asked about an initial setting of DEBUG for a channel is because oftentimes a channel can start and crash before you can type de-client --set-channel-loglevel
> And if I understand it, the --set-channel-loglevel is not sticky, you have to do it every time you restart the channel.
> 
> As far as the main debug level in /etc/decisionengine/decision_engine.conf, that does not affect the channel.
> I have that set, but the individual channels still defaulted to WARN and individual channels only contained WARN or higher until I did the --set-channel-loglevel.

yes, the idea is that if you need to debug channel you just set master log level to DEBUG. If it does not have any effect this needs to be fixed, this is, of course, not how it is supposed to work.

**Comment by goodenou** [comment]
Will someone please point me to a channel config file that I can use for testing this? The two channels I have been using do not show me this behavior.

**Comment by StevenCTimm** [comment]
This is the framework issue:
After a clean restart of the decision-engine:
[root@fermicloud117 ~]# de-client --print-engine-loglevel
DEBUG
[root@fermicloud117 ~]# de-client --get-channel-loglevel sample_gcebilling.jsonnet
WARNING
[root@fermicloud117 ~]# de-client --get-channel-loglevel AWS_Calculations_with_source_proxy.jsonnet
WARNING

---

There are no DEBUG messages showing in any of the channel logs.
I believe this is not the intended behavior.

Once I do de-client --set-channel-loglevel <channelname> DEBUG on all of the channels then the DEBUG messages come back.

As far as channels that crash almost immediately

At the moment the job_classification channel errors out within a few seconds as does the AWS_Calculations_with_source_proxy channel. I would suggest trying to run the job_classification channel since that requires no  credentials to run it.

For channels that regularly have some debug messages I would suggest the Nersc channel.  I can supply a credential to run it with if you require this.. Contact me out of band.

Steve Timm

**Comment by StevenCTimm** [comment]
There is another mystery too, namely that the routine AWS/sources/BillingInfo.py is configured to push out tons of debug messages from its own module code and I do not see them BUT I do see very verbose debug messages from all of the subroutines that it is calling in the AWS SDK.  (boto, s3transfer, etc).

**Comment by goodenou** [comment]
Hi Steve,
Did you change the channel log level setting in the config file? The default value is 
'global_channel_log_level':"WARNING"

**Comment by StevenCTimm** [comment]
I was not aware of that setting up until now.  I changed it now:

    "logger": {
	"log_file": "/var/log/decisionengine/decision_engine_log",
	"max_file_size": 200000000,
	"max_backup_count": 6,
	"log_level": "DEBUG",
        "global_channel_log_level": "DEBUG"
	},

It had no effect.

After clean restart of decision-engine all --get-channel-loglevel return WARNING as before,.

Also it seems that the de-client --reload-config option doesn't have any effect either, you have to restart the DE to pick up a changed /etc/decisionengine/decision_engine.conf file.

**Comment by StevenCTimm** [comment]
The global_channel_log_level setting now has the desired effect of setting all channels to DEBUG when it is set to debug.
I consider this problem to now be fixed.

**Comment by StevenCTimm** [comment]
Fixed, closing
