### ISSUE TITLE
Yum update on decisionengine rpm doesn't restart the service

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#134]

**Comment by knoepfel** [comment]
@StevenCTimm, did a yum update automatically restart the service for past RPMs?

**Comment by StevenCTimm** [comment]
I had never tried to do a yum update while the decision engine was live before so I had never tried it.
But given the structure of the RPM, I doubt that it ever did restart the decision engine.

I noticed it only when I went to install the new release candidate rpm  but found that it had been installed by yum auto-update a couple days before, but the DE had not restarted.

**Comment by DmitryLitvintsev** [comment]
It never restarted on update

**Comment by jcpunk** [comment]
Based on other RPMs provided by Red Hat, typically RPMs do not restart services.

**Comment by StevenCTimm** [comment]
OK we will close this one and leave this issue as it is.
