### ISSUE TITLE
Have de-client --print-product return different error message if product does not exist

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#153]
Right now if you 
de-client --print-product foo

and foo does not exist

the output is just a blank data block, the same as if it really was there and blank.  Could we flag a non-existent data block if it is not there?

**Comment by DmitryLitvintsev** [comment]
This just a bug.  I will fix it.

Supposed output was :

"Product foo: Not Found"

But the line was incorrectly indented. Is this what you want , or I can change to "does not exist" or "not produced by any module"

Dmitry


________________________________________

**Comment by DmitryLitvintsev** [comment]
this should fix it:

https://fermicloud140.fnal.gov/reviews/r/203/

Dmitry

________________________________________

**Comment by StevenCTimm** [comment]
This issue now appears to be fixed.  I get a message saying that the product does not exist.

**Comment by StevenCTimm** [comment]
Fixed in production, closing
