### ISSUE TITLE
yum update on decision engine rpm from python2 to python3 doesn't undo the symlinks

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#171]
The decision engine rpm (python2 version), makes 2 symlinks

/usr/sbin/decisionengine -> /usr/lib/python2.7/site-packages/decisionengine/framework/engine/DecisionEngine.py
/usr/bin/de-client -> /usr/lib/python2.7/site-packages/decisionengine/framework/engine/de_client.py

When the framework is updated with "yum update decisionengine" 
the symlinks do not get removed,.

On a clean install of the python3.6 rpms the symlinks do get made correctly.

**Comment by StevenCTimm** [comment]
I have manually fixed the symlinks on my machine for now,

**Comment by DmitryLitvintsev** [comment]
https://fermicloud140.fnal.gov/reviews/r/223/

**Comment by StevenCTimm** [comment]
Verified this was fixed with the latest release of the decisionengine 1.4.0rc2

**Comment by StevenCTimm** [comment]
Closing this, good in the release.
