### ISSUE TITLE
Log invocations of importlib

### ISSUE THREAD

**Issue by jcpunk** [HEPCloud/decisionengine#178]
When import lib changes our loaded modules, it should log out which modules are being added.

**Comment by StevenCTimm** [comment]
It is not clear that this has yet been done.  There do not appear to be any invocations of importlib logged in the current release (1.7)

**Comment by mambelli** [comment]
Uses of `importlib` in decisionengine (no use in decisionengine_modules):
1. `_create_module_instance` in TaskManager
2. dynamic load of psycopg2 libraries in postgresql.py
3. `create_datasource` in `DataSourceLoader` in dataspace.py 
I think only 1 and 3 should be logged, no need for 2.

**Comment by jcpunk** [comment]
I'm showing this as fixed by Lisa now.
