### ISSUE TITLE
Channel debug info now leaks into startup.log

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#188]
I am observing that a huge amount of debug information from the resource_request channel 
(and possibly other channels as well) is leaking into startup.log.
This cannot come from a logging configuration.  startup.log only catches stuff that is getting written to standard out or standard error. 

This is from the 1.4.0rc1 rpm.  This was not happening before.

**Comment by StevenCTimm** [comment]
To be specific it seems that there are two different outputs going to startup.log. 
One of them is coming from an externally included library (bill-calculator-hep-mapsacosta) 
which writes a lot of stuff to startup.log.. we have already notified the maintainer of this package to see if
we can do something about that.

The second one appears to be only the debug output from the resource_request channel.  At first I thought it was only the logic engine but it is that whole task manager, sources, transforms, logic engines and all.
All the channels are configured identically and they are all supposed to be in debug but this is the only one that is bleeding over into startup.log.  Most of this debug info is also available in resource_request.log as it should be.

**Comment by StevenCTimm** [comment]
Perhaps because this is the only channel which went into ERROR mode and got restarted?  Not sure.

**Comment by knoepfel** [comment]
This issue is addressed with PR #192 .

**Comment by StevenCTimm** [comment]
Initial testing of 1.4.0rc-2 rpm shows that this problem appears to have gone away but I want to check it in 
case of restarting a channel and make sure it is ok then.

**Comment by StevenCTimm** [comment]
I verified that even in the case of restarting a channel and in debug mode the logging information does not leak through to startup.log.  This can be closed when the release is cut.

**Comment by StevenCTimm** [comment]
Release is cut, closing this issue.
