### ISSUE TITLE
Can't restart resource_request channel with de-client --stop-channel / de-client --start-channel

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#189]
de-client -v --stop-channel resource_request
An error occurred while trying to access a DE server at 'http://localhost:8888'
Please ensure that the host and port names correspond to a running DE instance.
<Fault 1: "<class 'AttributeError'>:'NoneType' object has no attribute 'task_manager'">

channel: AWS_Calculations_with_source_proxy , id = 36276E7F-FB68-4A29-B736-413E97947BD4, state = STEADY   
channel: sample_gcebilling         , id = 602F0A9C-3C34-46E9-B161-49C0D370CD43, state = STEADY   
channel: Gce                , id = 817B8402-B4A2-4874-A6CB-033C5A9DD459, state = STEADY   
channel: Nersc               , id = 8BEB2096-D39F-4869-AB12-EEBCAB6318E6, state = STEADY   
channel: channel_aws_config_data      , id = 9416C0BE-DAEA-4081-B6C8-68B5532F6308, state = STEADY   
channel: AWSbilling             , id = 7AB6FAF0-D993-4E46-8B8D-E6A6787EE2CC, state = STEADY   
Channel resource_request is in ERROR state
channel: job_classification         , id = 4F4995F3-24CE-480C-ABC8-DDEAC91D4CB3, state = STEADY   
	state: State.STARTING

I also note that the 
"Channel resource_request is in ERROR state" message has changed not only the format of the 
previous message, but also the reported state, ERROR vs. OFFLINE.. operations has stuff that greps this output.
Is this going to continue this way, if so we will have to readjust the monitoring

Kyle reports he already has a patch.

For the record, the channel was expected to go into offline/error state in this configuration because we
had the timeout for the AWSBillingInfo SourcePRoxy set to 3 retries / 20 s which is known to be not enough time.

**Comment by StevenCTimm** [comment]
The patch now works (once I made the patched file executable)

I can stop and start the channel
and everything is steady

**Comment by StevenCTimm** [comment]
Kyle gave another patch to address the formatting issues, I will test that this afternoon

**Comment by StevenCTimm** [comment]
Reopened issue #189 NOT FIXED

[root@hepcsvc03 config.d]# de-client --status | grep -i state
channel: AWS_Calculations_with_source_proxy , id = 335FA1D5-1570-4C56-8059-B8380291B0C3, state = STEADY     
channel: AWSbilling                         , id = 96391A8D-6BC2-4823-A9B3-5517C25CACC1, state = STEADY     
channel: Gce                                , id = 13B6C693-7B36-43EA-B51B-8CE2526B1EFD, state = STEADY     
channel: Nersc                              , id = 1F1C03EC-029E-443E-A476-0CFE55C2157A, state = STEADY     
channel: channel_aws_config_data            , id = 2D80A28E-ADE0-4749-95CA-F72810859CF0, state = STEADY     
channel: job_classification                 , id = 1495E7EE-57EC-498F-AF9A-615C08B23E20, state = STEADY     
channel: resource_request                   , id = 0D503E59-A269-4A9E-9A38-1B6AA162EF7C, state = ERROR      
channel: sample_gcebilling                  , id = 45D686C5-A56B-4849-B744-23989C5333BF, state = STEADY

[root@hepcsvc03 config.d]# de-client --stop-channel resource_request
OK
[root@hepcsvc03 config.d]# de-client --start-channel resource_request


(hangs forever)

and all other de-client commands after that also hang.

**Comment by DmitryLitvintsev** [comment]
you are testing rc2?

**Comment by StevenCTimm** [comment]
yes I am testing rc2.

**Comment by StevenCTimm** [comment]
I consider this to be a blocking issue.
To reproduce:

set num_retries for the BillingInfoSourceProxy to be 3
restart the decision engine

The resource_Request channel will go into error because the AWS billing info information is not ready in time.

**Comment by StevenCTimm** [comment]
fermicloud155 is configured in this error configuration, with the resource_request channel in state ERROR.
Kyle and Dmitry have root access.

**Comment by knoepfel** [comment]
Hmm...interesting.  I just issued the following commands on fermicloud155:
```
[root@fermicloud155 ~]# de-client --status | grep -i state
channel: AWS_Calculations_with_source_proxy , id = FE4EAF95-5103-4E84-B148-3490268B4975, state = STEADY     
channel: AWSbilling                         , id = E3512BAD-3134-4BD6-8FD3-6E236499E4D1, state = STEADY     
channel: Gce                                , id = 5B8DCAE5-92D2-41D6-AC63-2194099D4B4D, state = STEADY     
channel: Nersc                              , id = 47C99E20-829F-48CA-B3F4-5768F8378553, state = STEADY     
channel: channel_aws_config_data            , id = 1637E135-D607-4AEA-8587-ABFF4DC6E923, state = STEADY     
channel: job_classification                 , id = 27E1E061-F817-442C-A947-909E7BFD6E2F, state = STEADY     
channel: resource_request                   , id = 9D7A014C-61FD-4CCC-A1F7-C777C603341B, state = ERROR      
channel: sample_gcebilling                  , id = B6AB41F8-FFEF-4A85-B1F0-1B222B32AE90, state = STEADY     
	state: State.SLEEPING
[root@fermicloud155 ~]# de-client --stop-channel resource_request
OK
[root@fermicloud155 ~]# de-client --start-channel resource_request
OK
```
and then a couple minutes later
```
[root@fermicloud155 ~]# de-client --status | grep resource_request | grep state
channel: resource_request                   , id = 2BA417AC-3BFC-4452-9081-88A89D4C7142, state = STEADY
```

**Comment by StevenCTimm** [comment]
I looked at this again with Kyle on hepcsvc03 which was the original machine where I saw the bug.  We were not able to reproduce this behavior.  There is an outside chance it could be some kind of a data race condition.  We should keep this open and examine the locking behavior of requests to the decision engine server.

**Comment by StevenCTimm** [comment]
This is now not considered a blocking issue.

**Comment by StevenCTimm** [comment]
I propose that we track the further occurrences of the hang in the new issue #213 that I have opened and close this one.
Closing this now.
