### ISSUE TITLE
Under certain circumstances the fetch of the "consumes" information fails but the channel does not go offline

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#207]
This was observed in the production 1.1 decisionengine release.

We observed that glideclient classads were not being sent to the factory and traced the problem to the following issue:

2020-10-11 13:23:33,077 - root - TaskManager - 110564 - GlideinRequestManifests - INFO - transform GlideinRequestManifests did not get consumes data in 300 seconds. E
xiting

This was on cmsde01 in cms_resource_request.log

Even though the key transform exited, the channel was not set offline.

We observed that in time the resource_request channel, which should run every 5 minutes, was only running every 30 minutes or so because the system was so slowed down.

This error cleared on restart.

We do not know where the process was caught.

This is the first time we have observed the 100% cpu.  We had one previous instance where glideclient classads were not being advertised to the factory.

We will look for this in the 1.4 release with higher debug levels enabled this time.

**Comment by mambelli** [comment]
Not happening anymore
