### ISSUE TITLE
Error when trying to run reaper in version 1.4.0

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#208]
de-reaper
Traceback (most recent call last):
  File "/usr/bin/de-reaper", line 23, in <module>
    config_file = policies.global_config_filename()
AttributeError: module 'decisionengine.framework.config.policies' has no attribute 'global_config_filename'

What should the attribute "global_config_filename" be set to?
Which section of the config file

**Comment by knoepfel** [comment]
This is an error in the Python code, not the configuration.  I will address it.

**Comment by StevenCTimm** [comment]
Now fixed, Closing this issue..
