### ISSUE TITLE
Add self tests for rpc_print_product types=True

### ISSUE THREAD

**Issue by jcpunk** [HEPCloud/decisionengine#218]
With the merge of #216  we should make sure to test the new feature on the public API.

**Comment by StevenCTimm** [comment]
de-client --print-product <product> --types 
works
de-client --print-product <product> --format vertical
works
de-client --print-product <product> --format column-names
works
de-client --print-product <product> --format json
works

de-client --print-product <product> --columns <column> --format <format>
works for all formats

de-client --print-product <product> --format <format> --types 
works for all formats

de-client --print-product <product> --columns ColumnName,ColumnName.type --types 
works

It took me a while to figure out what the syntax was to show a single column and its type in the --columns thing, that's
not obvious in the usage and I had forgotten from the earlier testing.

But I confirm it's all functional.

It appears that the code self-tests that this ticket requested are done as well.

Any objections to closing this ticket?  I have none.

**Comment by jcpunk** [comment]
I'm satisfied this is resolved.
