### ISSUE TITLE
Reaper error message on DE

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#237]
After a reboot on cmsde01 we saw the following error in startup.log:

Reaper.reap() failed with FATAL:  remaining connection slots are reserved for non-replication superuser connections

It is not clear why the reaper would have failed.  We have never seen this error message before.

**Comment by DmitryLitvintsev** [comment]
This means we run out of maximum connections limit on DB end which by default is 100
It should not happen under normal circumstances. Almost looks like there is busy loop with
connections opened fast.

So de fails to start ?"

Dmitry

________________________________________

**Comment by StevenCTimm** [comment]
Have asked Database people what the total number of DB connections allowed is.
As detailed in #236 the DE does eventually start but very slowly, and one channel is OFFLINE due to problems with the NERSC resource.

**Comment by StevenCTimm** [comment]
Database people come back and say the number of allowed connections is 100.  We only had 19 established ones every time we looked, so source of the reaper error remains unknown.. but has been reproducible in the corner case operationally that is described in issue #236--it happened each of three times we attempted to restart the DE.

**Comment by StevenCTimm** [comment]
We never got to the bottom of the total database connections allowed issue.  But this error hasn't happened again so I presume that it must be connected to the error condition we were in at the time, in which NERSC was down and NERSC-related sources were retrying 100x, thus putting high load on the DB.  See issue #236.  

The reaper error hasn't happened again since the day it was originally reported.

**Comment by StevenCTimm** [comment]
There are now no reaper messages in the log at all of any sort, even in full debug mode.

**Comment by StevenCTimm** [comment]
With the structured logging release the reaper thread messages are all there.
Closing this issue.
