### ISSUE TITLE
Decision engine can sometimes start up at boot time before network name resolution is working

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#253]
We observed a case where the decision engine attempted to start at reboot before network name resolution was working correctly.  Thus it was unable to find the database and just sat there in a confused state.

This could be mitigated by adding a network target to the systemd service file

After=network-online.target
Wants=network-online.target

**Comment by DmitryLitvintsev** [comment]
https://fermicloud140.fnal.gov/reviews/r/314/

**Comment by DmitryLitvintsev** [comment]
This has been addressed

**Comment by StevenCTimm** [comment]
Have observed that this fix is now in the release, will test shortly by rebooting the machine and see if it waits
for network to start.

**Comment by StevenCTimm** [comment]
Tested on fermicloud155--looks good but not a definitive test because the database is pointing to "localhost".. will 
hold open until we've tried this with an external DB on hepcsvc03

**Comment by StevenCTimm** [comment]
This is now verified to work under 1.6.1.  Closing this issue.
