### ISSUE TITLE
Unify ProcessingState with Reaper state management code

### ISSUE THREAD

**Issue by jcpunk** [HEPCloud/decisionengine#285]
I think the `ProcessingState` class from `decisionengine/framework/taskmanager/ProcessingState` can do the job if we add one more state `active`?

Then we can eliminate duplicate sync code.

Also, Reaper should be in its own `.py` file.....

**Comment by StevenCTimm** [comment]
Will this have any observable effect on the running DecisionEngine?

**Comment by jcpunk** [comment]
The state names will be different (to be come consistent with the existing workers).  The code I've got now also correctly watches the state of the Reaper process.  Right now when the reaper is reaping, nothing can interrupt that.  If you send a shutdown, the client returns "OK", but the reaper may not have seen the state change.  I've got some locking I've added in so that if you send a 'shutdown the reaper" signal, it is more consistent.

**Comment by StevenCTimm** [comment]
There is still absolutely no entries in any log about the reaper starting or stopping.
On all restarts I have done, we see de-client --status show the reaper wait for reaper_start_delay_seconds
(currently configured to be 1818) .. it shows STARTING during that time, and then immediately goes to SLEEPING.
Are there any other states that the reaper can have?

**Comment by jcpunk** [comment]
In the proposed patch, the reaper can have the following "running" states:

- BOOT
- IDLE
- ACTIVE
- STEADY

The 'BOOT' state only exists between the call to start the thread and actually starting it.

The 'IDLE' state is when the reaper is scheduled to run at some point in the future.

The 'ACTIVE' state is when the reaper is actually cleaning records.  Since the `timestamp` column is indexed, I'd expect the cleanup to be fairly quick.

The 'STEADY' state will probably only exist for a second or so at a time.  It is the 'reaper completed without issue state'.  Once the reaper completes it reschedules itself for another run in the future.

**Comment by jcpunk** [comment]
I've updated the PR to add some more logging points to track the run states

**Comment by StevenCTimm** [comment]
OK--now reading the text of this ticket I thought the PR mentioned above had already been merged to trunk 
and was part of the release I am testing at the moment.  Now I see it is not.  my apologies for the misunderstanding.

Will try to grab a build artifact of this PR in the next couple days but testing the 1.6.1 integration testing takes priority over that.
