### ISSUE TITLE
Taskmanager doesn't use/honor global log level

### ISSUE THREAD

**Issue by jcpunk** [HEPCloud/decisionengine#406]
My reading of the setup code [1] and the later invocations [2] seems to indicate that TaskManager isn't using the logger that we've already configured and setup.

[1]
https://github.com/HEPCloud/decisionengine/blob/master/src/decisionengine/framework/taskmanager/TaskManager.py#L141

[2]
https://github.com/HEPCloud/decisionengine/blob/master/src/decisionengine/framework/taskmanager/TaskManager.py#L193

**Comment by goodenou** [comment]
fixed in structured logging
