### ISSUE TITLE
Add auto-formatting of the code

### ISSUE THREAD

**Issue by mambelli** [HEPCloud/decisionengine#418]
We should add some pre-commit tools that will help make the code more uniform, future-proof, and deterministic:
- formatter (one of black, yapf, ...), so anyone can write in slightly different ways and this will make the code more uniform
- isort, to sort the imports (https://github.com/PyCQA/isort)
- pyupgrade, to keep the syntax future-proof (https://github.com/asottile/pyupgrade)
- some other code verifications

These and similar tools should be evaluated and a proposal should be discussed at the developers meeting and put in place as pre-commit checks and modifications after obtaining developers consensus.
See also the comments in PR #408 for an initial discussion.

**Comment by jcpunk** [comment]
I've prepared a limited presentation for our next meeting.
