### ISSUE TITLE
Struct Logging Self test errors with pytest-xdist

### ISSUE THREAD

**Issue by jcpunk** [HEPCloud/decisionengine#453]
Our current testsuite almost runs under `xdist`.  Alas, there appears to be an issue with how the tests are interacting with our new structured logging.

```
RuntimeError: Failed to create log: Unable to configure handler 'de_file_debug'
```

To replicate run `pytest -vv -n auto` against the current `HEAD`.

If we can get the tests to pass under xdist, that will greatly speed up our test suite (with-xdist: 135s, without-xdist: 611s)

**Comment by goodenou** [comment]
Fixed with PR 517
