### ISSUE TITLE
Logic engine messages show in the main DE log (1.6.99 post4)

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#456]
2021-07-20 03:04:03,644 - decisionengine - LogicEngine - INFO - {"event": "LE: c
alling evaluate_facts", "level": "info", "logger": "decisionengine", "module": "
LogicEngine", "timestamp": "2021-07-20 03:04:03"}
2021-07-20 03:04:03,684 - decisionengine - LogicEn

Logic Engines are always called as part of a channel and not from the framework itself.
It would seem that these messages should be part of a channel log.   As it is we cannot
see which channel called the Logic Engine.

**Comment by mambelli** [comment]
Fixed in 1.7.0 RC4 (1.6.99 post8)
