### ISSUE TITLE
Setuptools issues in decisionengine rpm

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#459]
The release notes of 1.7.0 say "Packaging via setuptools for both decisionengine and decisionengine_modules: RPM packages correctly install also all dependencies."

This is not quite true in the current release.  The rpm does not install all the dependencies at the moment, either by pip or by RPM.
Those dependencies which do not exist in EPEL have now been built as RPMS but the rpm does not
list them as requires as yet, and we have not yet added them to the repo. 

The RPM does, however, pull in python3-pip, python3-setuptools, and python3-wheel.
The version of python3-pip which comes from the RPM is not new enough to install some of the pip
packages that are needed for the modules.  the python3-pip from SL7 is 9.0.3.  21.1.3 is available and >20 
is needed to install the gcs-oauth2-boto-plugin pip packages and some others.  Further, if a python3-pip upgrade were released via rpm it would back-load the SL7 version and clobber the new version.

**Comment by StevenCTimm** [comment]
I believe the stock SL7 versions of python3-setuptools and python3-wheel are new enough, but they are by no means the newest.

**Comment by jcpunk** [comment]
> Further, if a python3-pip upgrade were released via rpm it would back-load the SL7 version and clobber the new version.

Only if you install the updated `pip` into `/usr/lib/python3.6/site-packages`.  If you install it into the local area (via `--user` as recommended by `pip`) or into `/usr/local/lib/python3.6/site-packages` (which is the default when run as root).  the PRM will not replace it.

**Comment by StevenCTimm** [comment]
The --user option isn't necessarily an option because some of the pip modules need to be available both to user decisionengine and user root.
I take your point about pip install  / pip3 install dumping into /usr/local/lib.  There was a time that this was not
the case and we got bit by yum updates but it does not seem to be the case anymore and indeed 2 versions of wheel, pip3, and setup tools are co-existing on the system ok.


So the only remaining issue here is actually modifying the release  notes to correct that the rpms as written
do not necessarily install all dependencies, at least not yet.

**Comment by jcpunk** [comment]
The release notes are now more accurate

**Comment by StevenCTimm** [comment]
Agreed-- will close this issue once the release is cut.
