### ISSUE TITLE
Request: Make postgresql migration script to migrate from old postgresql schema to new sqlalchemy schema

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#480]
Please detail the modifications that would have to be made to an existing database to modify the existing postgresql schema in production, to be compatible with the new schema as required by sqlalchemy.

**Comment by jcpunk** [comment]
This SQL should migrate the "old" schema to the one in use by SQLAlchemy.

It "should" be safe to run this against a schema in use by the "old" datasource (running the fixed version of 1.7.0 via PR #470)
as it merely adds some elements that are ignored by that DS.

We could "alter" the indexes to rename them, but then they would have different definitions for their various options.

This will probably leave some "Invisible" items with different names (internal constraints about PRIMARY KEYS and SEQUENCE elements) that we don't manage ourselves.

Depending on the size and fragmentation of the physical data on disk, this will take a long time.

```sql
ALTER TABLE dataproduct ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE header ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE metadata ADD COLUMN id SERIAL PRIMARY KEY;



DROP INDEX IF EXISTS i_taskmanager_datestamp;
DROP INDEX IF EXISTS i_taskmanager_sequence;
DROP INDEX IF EXISTS i_taskmanager_taskmanager_id;
CREATE INDEX ix_taskmanager_datestamp ON public.taskmanager USING brin (datestamp) WITH (autosummarize='on', pages_per_range='1024');
CREATE INDEX ix_taskmanager_name ON public.taskmanager USING hash (name);
CREATE INDEX ix_taskmanager_taskmanager_id ON public.taskmanager USING hash (taskmanager_id);

DROP INDEX IF EXISTS i_dataproduct_taskmanager_id;
DROP INDEX IF EXISTS i_dataproduct_generation_id;
DROP INDEX IF EXISTS i_dataproduct_key;
CREATE INDEX ix_dataproduct_generation_id ON public.dataproduct USING btree (generation_id) WITH (fillfactor='70');
CREATE INDEX ix_dataproduct_key ON public.dataproduct USING hash (key);
CREATE INDEX ix_dataproduct_taskmanager_id ON public.dataproduct USING hash (taskmanager_id);

DROP INDEX IF EXISTS i_header_taskmanager_id;
DROP INDEX IF EXISTS i_header_generation_id;
DROP INDEX IF EXISTS i_header_key;
CREATE INDEX ix_header_generation_id ON public.header USING btree (generation_id) WITH (fillfactor='50');
CREATE INDEX ix_header_key ON public.header USING hash (key);
CREATE INDEX ix_header_taskmanager_id ON public.header USING hash (taskmanager_id);

DROP INDEX IF EXISTS i_metadata_taskmanager_id;
DROP INDEX IF EXISTS i_metadata_generation_id;
DROP INDEX IF EXISTS i_metadata_key;
CREATE INDEX ix_metadata_generation_id ON public.metadata USING btree (generation_id) WITH (fillfactor='70');
CREATE INDEX ix_metadata_key ON public.metadata USING hash (key);
CREATE INDEX ix_metadata_state ON public.metadata USING hash (state);
CREATE INDEX ix_metadata_taskmanager_id ON public.metadata USING hash (taskmanager_id);



ALTER TABLE ONLY public.dataproduct
    ADD CONSTRAINT uq_dataproduct_taskmanager_id_generation_id_key UNIQUE (taskmanager_id, generation_id, key);
ALTER TABLE ONLY public.header
    ADD CONSTRAINT uq_header_taskmanager_id_generation_id_key UNIQUE (taskmanager_id, generation_id, key);
ALTER TABLE ONLY public.metadata
    ADD CONSTRAINT uq_metadata_taskmanager_id_generation_id_key UNIQUE (taskmanager_id, generation_id, key);
ALTER TABLE ONLY public.taskmanager
    ADD CONSTRAINT uq_taskmanager_squence_id_taskmanager_id UNIQUE (sequence_id, taskmanager_id);
```

**Comment by StevenCTimm** [comment]
Thanks.  I will try this on some postgresql-flavored dev database I don't care about and see if it works.

**Comment by jcpunk** [comment]
In theory, the "old" datasource can run on this schema... I'm curious if that is in fact true... not sure we need that option, but it migh tbe nice.

**Comment by jcpunk** [comment]
Hi Steve, just checking in on this.

**Comment by StevenCTimm** [comment]
I have not yet had time to try this, and won't have time before I go on vacation.
1.7.0rc2 continues to run on hepcsvc03 on a postgresql (non-sqlalchemy) db.

**Comment by StevenCTimm** [comment]
We figured out that, given the decisionengine user , we could do 
GRANT INSERT,SELECT, UPDATE,DELETE on table_name to decisionengine_write;
for each of 5 tables
and 
GRANT SELECT on table_name to decisionengine_read;

I am not sure if this type of thing could be added into the automatic sqlalchemy initialization.
