### ISSUE TITLE
systemctl start decision engine doesn't work

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#5]
When using the systemctl command as supplied in the rpm, the 
start command never exits, and thus after two minutes systemctl declares a timeout.
Commands that are executed in the "start" are supposed to exit to work with systemctl

**Comment by StevenCTimm** [comment]
Parag supplied a new systemd unit file that works to start/stop decision-engine with systemctl
but we have to remove the condor dependency on this unit (I replaced it with httpd).
and make sure it gets back into the next release of the framework.

**Comment by paragmhashilkar** [comment]
fixed in #17
