### ISSUE TITLE
Feature request:  have configuration file reflect PRODUCES, CONSUMES

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#6]
The PRODUCES and CONSUMES fields of sources and transforms are not evident in the configuration file.  It would be nice to not have to examine the code of the modules to figure this out.

More in general it would be good to have some kind of a syntax/content checker for decision channel config files which are written in python.

**Comment by paragmhashilkar** [comment]
Currently there is no way to include PRODUCES an CONSUMES in the configuration. One of the gripes I had from the beginning but I also understand why thats not possible. Assigning the syntax checker functionality to Dmitry.

**Comment by DmitryLitvintsev** [comment]
Also , for Steve : 

python /path/to/Config.conf 

will answer if your config has syntax errors

**Comment by StevenCTimm** [comment]
Dmitry's recent feature additions to de-client which allow to print the PRODUCES and CONSUMES of all running channels are sufficient to address this concern.  This issue can be closed.

**Comment by StevenCTimm** [comment]
I had marked earlier that this issue can be closed but I do hope it will be addressed as part of the re-examination of the PRODUCES, CONSUMES syntax.

**Comment by StevenCTimm** [comment]
This is now in testing in the 1.7 release candidate, it appears to be working thus far.

**Comment by StevenCTimm** [comment]
This feature is now complete and I have tested it, including the templated config.
