### ISSUE TITLE
New DE 2.0rc2 regularly takes 2-3 minutes to shut down

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#626]
Believe this may be due to previous shutdown timeout configuration being lost in some of the config file refactoring, 
will check.  but need a faster and more reliable shutdown.  (This technically could be a decisionengine_modules issue
since much of the time is spent in calling publishers). 

as far as I can tell, de-client --stop-channel resource request doesn't work at all, 
systemctl stop decisionengine regularly takes a couple minutes.

**Comment by knoepfel** [comment]
This issue should be fixed with PR #636.

**Comment by StevenCTimm** [comment]
Now fixed with pr 648 we can close this one whenever that is merged to trunk and in a release
