### ISSUE TITLE
de-client --status stalls whenever channels are not yet in STEADY state

### ISSUE THREAD

**Issue by knoepfel** [HEPCloud/decisionengine#639]
This makes it very difficult to debug.  We should investigate whether the protected (i.e. blocking) access to the channel workers can be relaxed.

**Comment by knoepfel** [comment]
It is not yet clear if the stall was due to unnecessary blocking of the channel workers during the `de-client --status` call, or whether it is something deeper down (e.g. locking due to changing the processing state of the channel).  A forthcoming PR may address this issue.

**Comment by StevenCTimm** [comment]
PR 648 appears to have not fixed this issue.. still takes 5 minutes 28 seconds to get output from de-client --status
