### ISSUE TITLE
Version 1.1.0-1 decisionengine rpm has bad requires

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#78]
rpm -qp --requires decisionengine-1.1.0-1_py2.7.x86_64.rpm 
/bin/bash
/bin/sh
/bin/sh
/bin/sh
/sbin/service
/usr/bin/env
/usr/sbin/useradd
boost-python2.7 >= 1.53.0
boost-python2.7-devel >= 1.53.0
boost-regex >= 1.53.0
boost-system >= 1.53.0
config(decisionengine) = 1.1.0-1_py2.7
libLogicEngine.so()(64bit)
libboost_python.so.1.53.0()(64bit)
libboost_regex.so.1.53.0()(64bit)
libboost_system.so.1.53.0()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libm.so.6()(64bit)
libpython2.7.so.1.0()(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
python(abi) = 2.7
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)

---

In particular it is requiring boost-python2.7 >= 1.53.0
which is not supplied by the stock boost-python rpm in SL7.
Should just be requiring boost-python

**Comment by StevenCTimm** [comment]
If I understand it right this is due to the following 2 lines in the specfile

Requires:       boost-python%pyver-devel >= 1.53.0
Requires:       boost-python%pyver >= 1.53.0

In native SL7 (not any virtual environment) python 2.7 is stock python and the %pyver
macro being appended results in calling for requirements that don't exist.

**Comment by StevenCTimm** [comment]
The rpm now installs and has the correct requirement but when I install I still get a warning

root@fermicloud133 x86_64]# rpm -i decisionengine-1.1.0-1_py2.7.x86_64.rpm 
pam_tally2: Couldn't create /var/log/tallylog: Permission denied
pam_tally2: Authentication error
useradd: failed to reset the tallylog entry of user "decisionengine"

As I say, the rpm still installs despite this warning, I will soon find out if it is functional.
Anyone should be able to reproduce this on a vanilla SL7 fermicloud VM. (which by default have SELinux set to enforcing). 
 I will try without SELinux (which the production system is set to) and see if that makes a difference).

**Comment by StevenCTimm** [comment]
Without SElinux the rpm installed without warnings so I suspect that the warning is selinux-related and not of concern at the moment, since the DE does and must run without SELinux for other reasons in any case.

**Comment by StevenCTimm** [comment]
There is also a problem in the python3.6 first version of the rpm..It requires
boost-python3.6 but what is supplied by the boost-python36 rpm is boost-python36.

Let me know when the 3.6 framework rpm is rebuilt with the pull request.

**Comment by gartung** [comment]
Pull the rpms from this link
https://github.com/HEPCloud/decisionengine/suites/603049343/artifacts/4490021
This will have the latest rpms which have a dependence on the boost-python36 rpm

**Comment by StevenCTimm** [comment]
Yes, that 3.6 rpm installs ok Thank you.. this issue can now be considered resolved.

**Comment by StevenCTimm** [comment]
Except for one thing--although the decisionengine 3.6 rpm and decisionengine_modules 3.6 rpms 
install ok they still dump all the files in /usr/lib/python2.7/site-packages
Something is not right with that.

**Comment by StevenCTimm** [comment]
Also--was it the plan to just remove all #! from the python3.x repository?

**Comment by DmitryLitvintsev** [comment]
yes, on the master all removed except 3 relevant ones

**Comment by StevenCTimm** [comment]
What's the resolution of the python 3.6 rpm still dumping all the files into /usr/lib/python2.7 directories?  Has that been fixed?

**Comment by gartung** [comment]
That is what happens when you add back building 3.6 rpms on the 1.1 branch. I need to update the spec to incorporate the changes for 3.6 build from master.

**Comment by DmitryLitvintsev** [comment]
1.1 was created *after* 3.6 sport and builds were added, they just weren't correct/tested. Will you be able to fix it? IMO it is important step where we had almost unmodified code base and support for 2.7 and 3.6. Allows Steve to potentially test 3.6.

**Comment by gartung** [comment]
I am working on a fix now.

**Comment by gartung** [comment]
@StevenCTimm please test the rpms in this tar file
https://github.com/HEPCloud/decisionengine/suites/619120367/artifacts/4858577

**Comment by StevenCTimm** [comment]
Thanks Patrick I will let you know in a little while.

**Comment by gartung** [comment]
Hang on. The py3 rpm has issues. Debugging now.

**Comment by gartung** [comment]
Pull the tar file from here
https://github.com/HEPCloud/decisionengine/suites/619191236/artifacts/4860001
```
tar xf rpmbuild-3.6.tar 
yum --enablerepo epel install -y var/tmp/decision-engine-ci/rpm/decisionengine/RPMS/x86_64/decisionengine-1.1.0-1_py3.6.x86_64.rpm
```

**Comment by gartung** [comment]
If you have a github personal access token you can download directly with 
```
curl -v -L -u github_user:github_pat -o rpms.zip https://api.github.com/repos/hepcloud/decisionengine/actions/artifacts/4860001/zip
```

**Comment by StevenCTimm** [comment]
The  decisionengine-1.1.0-1_py3.6.x86_64 rpm in the latest tar file now installs clean and puts the files in the /usr/lib/python3.6/ area as it should.

Do we have a matching decisionengine-standard-library rpm that does the same?

**Comment by gartung** [comment]
I am not familiar with the decisionengine-standard-library rpm.

**Comment by gartung** [comment]
It appears to be commented out in the spec file.

**Comment by StevenCTimm** [comment]
It's the one that is built from the decisionengine_modules repo
And it has the same problem in the rpm build, namely that everything winds up in /usr/lib/python2.7/site-packages for both the 2.7 and 3.6 builds.
What did you fix on the 3.6 side decisionengine.spec, we should just have to make the same change in the decisionengine-standard-library.spec

**Comment by DmitryLitvintsev** [comment]
Patrick, it is in decisionengine_modules repository.

**Comment by gartung** [comment]
I uncommented the sections in both spec files related to standard-library on my latest pull request. Look for the artifacts once the rpmbuild action completes.

**Comment by DmitryLitvintsev** [comment]
I don't think this is pertinent.

**Comment by gartung** [comment]
Sorry I will submit a PR to fix decisionengine_modules.

**Comment by DmitryLitvintsev** [comment]
Steve can you create similar issue for decisionengine_modules ?

**Comment by gartung** [comment]
https://github.com/HEPCloud/decisionengine_modules/pull/211

**Comment by StevenCTimm** [comment]
Done
https://github.com/HEPCloud/decisionengine_modules/issues/212
is the issue.
So this one can be closed out.
