### ISSUE TITLE
Flexible log level per channel

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine#84]
Currently the log level of decision engine is hardcoded to WARN. 

   * It is required that the initial log level for all channels to be configurable and defined in configuration,
   * Log level should be modifiable at the run time per channel like so:
```
   de-client --log-level=DEBUG
   de-client --log-level=DEBUG <channel name>
```

**Comment by StevenCTimm** [comment]
Is this supposed to be in the current 1.2 branch?  I thought this feature was already done and pushed.

**Comment by DmitryLitvintsev** [comment]
Not merged yet.

**Comment by goodenou** [comment]
Merge #105 dealt with these issues.
