### ISSUE TITLE
Make list of ignored warnings consistent between GitHub actions and Travis (pep8speak)

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine#85]
I am getting these warnings: 

```
Line 1129:13: W503 line break before binary operator
```

Whereas pylint run by GitHub actions does not generate these. Please make pep8speak list of ignored pep8 errors consistent with GitHub actions. 

Current setting:

```
build/scripts/run_pep8.sh:    PEP8_OPTIONS="--ignore=E261,E265,E302,E303,E501,E129,E221,E241,E272,E731,E1004,W503,W504,F999,N801,N813,N814"
```

This needs to be done for both repos : decsionenine and decisionengine_modules

**Comment by jcpunk** [comment]
I'm showing for decision engine:

https://github.com/HEPCloud/decisionengine/blob/master/.pep8speaks.yml#L9
https://github.com/HEPCloud/decisionengine/blob/master/build/scripts/run_pylint.sh#L71

These both seem to run W503.... They are not identical however.  I'll get that fixed up and check de_modules.

**Comment by jcpunk** [comment]
Fixes merged.
