### ISSUE TITLE
Change install script of decisionengine rpm 

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#95]
In the decisionengine rpm the decisionengine user is created with home directory /var/lib/decisionengine and no shell.
It should be a home directory of /home/decisionengine and a /bin/bash shell.

**Comment by DmitryLitvintsev** [comment]
Steve. I think I know where it comes from. Isn't it a standard? Say postgres user has 
/var/lib/pgsql as home

**Comment by DmitryLitvintsev** [comment]
```c0f3c3c8 (Parag Mhashilkar  2018-06-11 14:33:39 -0500 156)     useradd -r -g  %{de_user} -d /var/lib/decisionengine \
c0f3c3c8 (Parag Mhashilkar  2018-06-11 14:33:39 -0500 157)     -c "Decision Engine user" -s /sbin/nologin -m %{de_user}
```

**Comment by DmitryLitvintsev** [comment]
```
c0f3c3c8 (Parag Mhashilkar  2018-06-11 14:33:39 -0500 156)     useradd -r -g  %{de_user} -d /var/lib/decisionengine \
c0f3c3c8 (Parag Mhashilkar  2018-06-11 14:33:39 -0500 157)     -c "Decision Engine user" -s /sbin/nologin -m %{de_user}
```

**Comment by DmitryLitvintsev** [comment]
Has always been like that

**Comment by StevenCTimm** [comment]
Yes I agree it's always been like that.  I guess we can override with puppet as we have done before, at least as long as we are still using puppet.

**Comment by StevenCTimm** [comment]
I will close this issue as we have ways to override the home directory issue in puppet and if the home directory and user/group already exist before the rpm is installed it won't make new directory.
